import { Metadata } from "next";
import { companyInfo } from "@/constants/content";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms and conditions for using Optiveon LLC services and platform.",
};

export default function TermsPage() {
  return (
    <section className="py-[160px] min-h-screen">
      <div className="container max-w-4xl">
        <h1 className="text-4xl font-bold mb-lg">Terms of Service</h1>
        <p className="text-foreground-muted text-sm mb-3xl">
          Last Updated: January 2024
        </p>

        <div className="prose prose-invert max-w-none">
          <p className="text-foreground-secondary leading-relaxed mb-xl">
            These Terms of Service (&quot;Terms&quot;) govern your access to and
            use of the services, website, and applications (collectively,
            &quot;Services&quot;) provided by Optiveon LLC (&quot;Company,&quot;
            &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing or
            using our Services, you agree to be bound by these Terms.
          </p>

          <Section title="1. Acceptance of Terms">
            <p>
              By creating an account, accessing, or using our Services, you
              acknowledge that you have read, understood, and agree to be bound
              by these Terms and our Privacy Policy. If you do not agree to
              these Terms, you may not access or use our Services.
            </p>
          </Section>

          <Section title="2. Description of Services">
            <p>
              Optiveon provides market research tools, data analysis platforms,
              and related technology services. Our Services include:
            </p>
            <ul>
              <li>Market data analysis and visualization tools</li>
              <li>Algorithmic research and backtesting capabilities</li>
              <li>Signal generation and alert systems</li>
              <li>API access for data integration</li>
            </ul>
          </Section>

          <Section title="3. Important Disclaimers">
            <Subsection title="3.1 No Investment Advice">
              <p>
                <strong>
                  Our Services are for research and educational purposes only.
                </strong>{" "}
                Nothing provided through our Services constitutes investment
                advice, financial advice, trading advice, or any other sort of
                advice. You should not treat any of our content as such.
              </p>
            </Subsection>

            <Subsection title="3.2 No Recommendation">
              <p>
                We do not recommend that any financial instrument should be
                bought, sold, or held by you. We do not make any representation
                or warranty regarding any trading strategy or the accuracy of
                signals generated by our systems.
              </p>
            </Subsection>

            <Subsection title="3.3 Your Own Research">
              <p>
                You are solely responsible for conducting your own due diligence
                and making your own investment decisions. Before making any
                financial decisions, you should seek advice from a qualified and
                licensed financial advisor.
              </p>
            </Subsection>
          </Section>

          <Section title="4. Eligibility">
            <p>To use our Services, you must:</p>
            <ul>
              <li>Be at least 18 years of age</li>
              <li>Have the legal capacity to enter into a binding contract</li>
              <li>
                Not be prohibited from using the Services under applicable laws
              </li>
              <li>
                Comply with all applicable laws and regulations in your
                jurisdiction
              </li>
            </ul>
          </Section>

          <Section title="5. Account Registration">
            <p>
              To access certain features, you must create an account. You agree
              to:
            </p>
            <ul>
              <li>Provide accurate, current, and complete information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized access</li>
              <li>Be responsible for all activity under your account</li>
            </ul>
          </Section>

          <Section title="6. Subscription and Payment">
            <Subsection title="6.1 Fees">
              <p>
                Certain Services require payment of fees. All fees are quoted in
                US dollars and are non-refundable unless otherwise stated.
              </p>
            </Subsection>

            <Subsection title="6.2 Billing">
              <p>
                Subscription fees are billed in advance on a monthly or annual
                basis. Your subscription will automatically renew unless you
                cancel before the renewal date.
              </p>
            </Subsection>

            <Subsection title="6.3 Price Changes">
              <p>
                We reserve the right to change our prices with 30 days&apos;
                notice. Price changes will take effect at the start of your next
                billing cycle.
              </p>
            </Subsection>
          </Section>

          <Section title="7. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>Use the Services for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the Services</li>
              <li>Reverse engineer, decompile, or disassemble the Services</li>
              <li>Share your account credentials with others</li>
              <li>Resell or redistribute our Services without authorization</li>
              <li>
                Use automated systems to access the Services beyond permitted
                API usage
              </li>
            </ul>
          </Section>

          <Section title="8. Intellectual Property">
            <p>
              All content, features, and functionality of our Services,
              including but not limited to software, algorithms, text, graphics,
              logos, and trademarks, are the exclusive property of Optiveon LLC
              and are protected by intellectual property laws.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              <strong>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, OPTIVEON LLC SHALL NOT
                BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
                OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
              </strong>
            </p>
            <ul>
              <li>Loss of profits, revenue, or data</li>
              <li>Trading losses or investment losses</li>
              <li>Business interruption</li>
              <li>Cost of substitute services</li>
            </ul>
            <p className="mt-md">
              Our total liability shall not exceed the amount paid by you for
              the Services in the twelve (12) months preceding the claim.
            </p>
          </Section>

          <Section title="10. Disclaimer of Warranties">
            <p>
              THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS
              AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
              IMPLIED. WE DISCLAIM ALL WARRANTIES, INCLUDING MERCHANTABILITY,
              FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </Section>

          <Section title="11. Indemnification">
            <p>
              You agree to indemnify, defend, and hold harmless Optiveon LLC and
              its officers, directors, employees, and agents from any claims,
              damages, losses, liabilities, and expenses arising from your use
              of the Services or violation of these Terms.
            </p>
          </Section>

          <Section title="12. Termination">
            <p>
              We may suspend or terminate your access to the Services at any
              time for any reason, including violation of these Terms. Upon
              termination, your right to use the Services will immediately
              cease.
            </p>
          </Section>

          <Section title="13. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of the State of Texas, without regard to its conflict of
              law provisions. Any disputes shall be resolved in the courts
              located in Travis County, Texas.
            </p>
          </Section>

          <Section title="14. Contact Information">
            <p>For questions about these Terms, please contact us at:</p>
            <p className="mt-md">
              <strong>{companyInfo.name}</strong>
              <br />
              {companyInfo.address.street}
              <br />
              {companyInfo.address.suite}
              <br />
              {companyInfo.address.city}, {companyInfo.address.state}{" "}
              {companyInfo.address.zip}
              <br />
              Email:{" "}
              <a
                href={`mailto:${companyInfo.email}`}
                className="text-primary-light hover:text-accent"
              >
                {companyInfo.email}
              </a>
            </p>
          </Section>
        </div>
      </div>
    </section>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-3xl">
      <h2 className="text-2xl font-semibold mb-md">{title}</h2>
      <div className="text-foreground-secondary leading-relaxed space-y-md [&_ul]:ml-xl [&_ul]:list-disc [&_ul]:space-y-sm [&_li]:text-foreground-secondary">
        {children}
      </div>
    </div>
  );
}

function Subsection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-xl">
      <h3 className="text-lg font-medium mb-sm">{title}</h3>
      <div className="space-y-md">{children}</div>
    </div>
  );
}
