import { PricingTier } from "@/types";

export const pricingTiers: PricingTier[] = [
  {
    plan: "STARTER",
    slug: "starter",
    name: "Starter",
    description: "For individual researchers and analysts",
    price: 99,
    period: "/month",
    features: [
      "Real-time market data",
      "50+ technical indicators",
      "Basic signal alerts",
      "Email support",
    ],
    cta: "Get Started",
    href: "/checkout?plan=starter",
  },
  {
    plan: "PROFESSIONAL",
    slug: "professional",
    name: "Professional",
    description: "For serious traders and small teams",
    price: 299,
    period: "/month",
    features: [
      "Everything in Starter",
      "Advanced signal generation",
      "Backtesting suite",
      "API access (10K calls/day)",
      "Priority support",
    ],
    cta: "Get Started",
    href: "/checkout?plan=professional",
    featured: true,
    badge: "Recommended",
  },
  {
    plan: "ENTERPRISE",
    slug: "enterprise",
    name: "Enterprise",
    description: "For institutions and trading firms",
    price: null,
    priceLabel: "Custom",
    features: [
      "Everything in Professional",
      "Unlimited API access",
      "Custom integrations",
      "Dedicated account manager",
      "SLA guarantee",
    ],
    cta: "Contact Sales",
    href: "/checkout?plan=enterprise",
  },
];
